# Generated by Django 4.0.4 on 2022-04-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40)),
                ('phone', models.IntegerField(max_length=12)),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
